[2024-06-16T02:49:40.777-0300] {scheduler_job_runner.py:843} ERROR - Executor reports task instance <TaskInstance: import_github_data_to_postgres.download_file_from_github manual__2024-06-16T05:44:27.972947+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
